# Generated by Django 2.1.4 on 2018-12-23 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsTEKS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numQ', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('TEKS', models.CharField(choices=[('5.2B', '5.2B Compare and Order Decimals'), ('5.4A', '5.4A Prime & Composite'), ('5.3K', '5.3K Add & Subtract Decimals'), ('5.4F', '5.4F Order of Operations'), ('5.3E', '5.3E Multiply Decimals'), ('5.3G', '5.3G Divide Decimals'), ('5.3K', '5.3K Add & Subtract Fractions'), ('5.3B', '5.3B Multiply Whole Numbers'), ('5.3C', '5.3C Divide Whole Numbers'), ('5.3L', '5.3L Divide Fractions'), ('5.4B', '5.4B Represent & Solve Multi-Step Equations'), ('5.4C', '5.4C Tables, Patterns, Equations, Graphs'), ('5.4H', '5.4H Perimeter Area Volume'), ('5.5A', '5.5A Classify Figures'), ('5.8C', '5.8C Coordinate Grid')], default='green', max_length=10)),
            ],
        ),
    ]
